/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sms;

import java.awt.Color;
import javax.swing.*;
import java.sql.*;
import java.util.*;
import java.util.regex.Pattern;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Census
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
//        LoadCatgory();
    }
    int key = 0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jLabel16 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        productbtn = new javax.swing.JButton();
        userbtn = new javax.swing.JButton();
        categorybtn = new javax.swing.JButton();
        logoutbtn = new javax.swing.JButton();
        billingbtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        dashboardtabpanel = new javax.swing.JTabbedPane();
        billpanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        billtable = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        closelbl = new javax.swing.JLabel();
        minimizelbl = new javax.swing.JLabel();
        productpanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        pricetxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        producttxt = new javax.swing.JTextField();
        quantitytxt = new javax.swing.JTextField();
        categorycombo = new javax.swing.JComboBox<>();
        productScrollPane4 = new javax.swing.JScrollPane();
        producttable = new javax.swing.JTable();
        Addproductbtn = new javax.swing.JButton();
        Updateproductbtn = new javax.swing.JButton();
        Deleteproductbtn = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        searchcategorytxt = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        closelbl1 = new javax.swing.JLabel();
        minimizelbl1 = new javax.swing.JLabel();
        categorypanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        catnametxt = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        categoryScrollPane2 = new javax.swing.JScrollPane();
        categorytable = new javax.swing.JTable();
        updatecategorybtn = new javax.swing.JButton();
        addcategorybtn = new javax.swing.JButton();
        deletecategorybtn = new javax.swing.JButton();
        closelbl2 = new javax.swing.JLabel();
        minimizelbl2 = new javax.swing.JLabel();
        userpanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fullnametxt = new javax.swing.JTextField();
        useremailtxt = new javax.swing.JTextField();
        userphonetxt = new javax.swing.JTextField();
        userpasswordtxt = new javax.swing.JPasswordField();
        usertypecombo = new javax.swing.JComboBox<>();
        adduserbtn = new javax.swing.JButton();
        deleteuserbtn = new javax.swing.JButton();
        updateuserbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        userstable = new javax.swing.JTable();
        errorlabel = new javax.swing.JLabel();
        passwordcheck = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        closelbl3 = new javax.swing.JLabel();
        minimizelbl3 = new javax.swing.JLabel();

        jScrollPane3.setViewportView(jTree1);

        jLabel16.setText("jLabel16");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Dashboard");

        productbtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        productbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sms/icons/icons8-product-20.png"))); // NOI18N
        productbtn.setText("Product");
        productbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productbtnActionPerformed(evt);
            }
        });

        userbtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        userbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sms/icons/icons8-user-20.png"))); // NOI18N
        userbtn.setText("  User");
        userbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userbtnActionPerformed(evt);
            }
        });

        categorybtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        categorybtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sms/icons/icons8-category-20.png"))); // NOI18N
        categorybtn.setText("Category");
        categorybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categorybtnActionPerformed(evt);
            }
        });

        logoutbtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        logoutbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sms/icons/icons8-power-button-20.png"))); // NOI18N
        logoutbtn.setText("Logout");
        logoutbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutbtnMouseClicked(evt);
            }
        });
        logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbtnActionPerformed(evt);
            }
        });

        billingbtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        billingbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sms/icons/icons8-bill-20.png"))); // NOI18N
        billingbtn.setText("SELLS");
        billingbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billingbtnActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(255, 204, 255));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sms/icons/icons8-clothes-shop-66.png"))); // NOI18N

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Admin");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logoutbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(productbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(billingbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(userbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(categorybtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addGap(11, 11, 11)))
                                .addGap(0, 12, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(userbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(categorybtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(productbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(billingbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(logoutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        dashboardtabpanel.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        dashboardtabpanel.setToolTipText("tab4");
        dashboardtabpanel.setName("tab"); // NOI18N

        billpanel.setBackground(new java.awt.Color(153, 153, 255));
        billpanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                billpanelComponentShown(evt);
            }
        });

        billtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        billtable.setShowGrid(true);
        jScrollPane2.setViewportView(billtable);

        jLabel19.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        jLabel19.setText("SELLS OVERVIEW");

        closelbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sms/icons/icons8-close-16.png"))); // NOI18N
        closelbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closelblMouseClicked(evt);
            }
        });

        minimizelbl.setForeground(new java.awt.Color(204, 0, 204));
        minimizelbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sms/icons/icons8-line-15 (1).png"))); // NOI18N
        minimizelbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizelblMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout billpanelLayout = new javax.swing.GroupLayout(billpanel);
        billpanel.setLayout(billpanelLayout);
        billpanelLayout.setHorizontalGroup(
            billpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(billpanelLayout.createSequentialGroup()
                .addGroup(billpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(billpanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 22, Short.MAX_VALUE))
                    .addGroup(billpanelLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(minimizelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(closelbl)))
                .addContainerGap())
        );
        billpanelLayout.setVerticalGroup(
            billpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, billpanelLayout.createSequentialGroup()
                .addGroup(billpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(billpanelLayout.createSequentialGroup()
                        .addContainerGap(14, Short.MAX_VALUE)
                        .addComponent(jLabel19))
                    .addGroup(billpanelLayout.createSequentialGroup()
                        .addGroup(billpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(closelbl)
                            .addComponent(minimizelbl))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        dashboardtabpanel.addTab("b", billpanel);

        productpanel.setBackground(new java.awt.Color(0, 102, 51));
        productpanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                productpanelComponentShown(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 51));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sms/icons/icons8-supplier-65.png"))); // NOI18N
        jLabel10.setText("Manage Product");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 153));
        jLabel11.setText("Quantity");

        pricetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pricetxtActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 153));
        jLabel12.setText("Price");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 153));
        jLabel13.setText("Category");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 153));
        jLabel14.setText("Product Name");

        categorycombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categorycomboActionPerformed(evt);
            }
        });

        productScrollPane4.setBackground(new java.awt.Color(255, 255, 255));
        productScrollPane4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        productScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);

        producttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Product Name", "Quantity", "Price", "Category"
            }
        ));
        producttable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                producttableMouseClicked(evt);
            }
        });
        productScrollPane4.setViewportView(producttable);

        Addproductbtn.setBackground(new java.awt.Color(0, 0, 255));
        Addproductbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Addproductbtn.setForeground(new java.awt.Color(255, 255, 255));
        Addproductbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sms/icons/icons8-add-20 (1)_1.png"))); // NOI18N
        Addproductbtn.setText("Add");
        Addproductbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddproductbtnActionPerformed(evt);
            }
        });

        Updateproductbtn.setBackground(new java.awt.Color(255, 153, 0));
        Updateproductbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Updateproductbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sms/icons/icons8-edit-20.png"))); // NOI18N
        Updateproductbtn.setText("Update");
        Updateproductbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateproductbtnMouseClicked(evt);
            }
        });
        Updateproductbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateproductbtnActionPerformed(evt);
            }
        });

        Deleteproductbtn.setBackground(new java.awt.Color(255, 0, 0));
        Deleteproductbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Deleteproductbtn.setForeground(new java.awt.Color(255, 255, 255));
        Deleteproductbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sms/icons/icons8-trash-20 (1).png"))); // NOI18N
        Deleteproductbtn.setText("Delete");
        Deleteproductbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteproductbtnMouseClicked(evt);
            }
        });

        jLabel15.setForeground(new java.awt.Color(255, 255, 51));
        jLabel15.setText("Search by Category");

        closelbl1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sms/icons/icons8-close-16.png"))); // NOI18N
        closelbl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closelbl1MouseClicked(evt);
            }
        });

        minimizelbl1.setForeground(new java.awt.Color(204, 0, 204));
        minimizelbl1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sms/icons/icons8-line-15 (1).png"))); // NOI18N
        minimizelbl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizelbl1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout productpanelLayout = new javax.swing.GroupLayout(productpanel);
        productpanel.setLayout(productpanelLayout);
        productpanelLayout.setHorizontalGroup(
            productpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productpanelLayout.createSequentialGroup()
                .addGroup(productpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(productpanelLayout.createSequentialGroup()
                        .addGroup(productpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(productpanelLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(70, 70, 70))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, productpanelLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(producttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)))
                        .addGroup(productpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(productpanelLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel11))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, productpanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(quantitytxt, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(15, 15, 15))
                    .addGroup(productpanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(Addproductbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(productpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(productpanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(productpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(pricetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(productpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(categorycombo, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(productpanelLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(Deleteproductbtn)))
                .addContainerGap(15, Short.MAX_VALUE))
            .addComponent(jSeparator3)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, productpanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchcategorytxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(192, 192, 192))
            .addComponent(productScrollPane4)
            .addGroup(productpanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(productpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(Updateproductbtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(minimizelbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closelbl1)
                .addContainerGap())
        );
        productpanelLayout.setVerticalGroup(
            productpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productpanelLayout.createSequentialGroup()
                .addGroup(productpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(productpanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(productpanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(productpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(minimizelbl1)
                            .addComponent(closelbl1))))
                .addGroup(productpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(productpanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(productpanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(productpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(productpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(quantitytxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pricetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(categorycombo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(producttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(75, 75, 75)
                .addGroup(productpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Addproductbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Deleteproductbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Updateproductbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(productpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchcategorytxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addComponent(productScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        dashboardtabpanel.addTab("p", productpanel);

        categorypanel.setBackground(new java.awt.Color(153, 153, 153));
        categorypanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                categorypanelComponentShown(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sms/icons/icons8-manage-50 (1).png"))); // NOI18N
        jLabel8.setText("Manage Category");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Category Name");

        categoryScrollPane2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        categoryScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        categorytable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "id", "Category Name"
            }
        ));
        categorytable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                categorytableMouseClicked(evt);
            }
        });
        categoryScrollPane2.setViewportView(categorytable);

        updatecategorybtn.setBackground(new java.awt.Color(255, 153, 0));
        updatecategorybtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        updatecategorybtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sms/icons/icons8-edit-20.png"))); // NOI18N
        updatecategorybtn.setText("Update");
        updatecategorybtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        updatecategorybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatecategorybtnActionPerformed(evt);
            }
        });

        addcategorybtn.setBackground(new java.awt.Color(0, 204, 0));
        addcategorybtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addcategorybtn.setForeground(new java.awt.Color(255, 255, 255));
        addcategorybtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sms/icons/icons8-add-20 (1).png"))); // NOI18N
        addcategorybtn.setText("Add");
        addcategorybtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addcategorybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcategorybtnActionPerformed(evt);
            }
        });

        deletecategorybtn.setBackground(new java.awt.Color(255, 0, 0));
        deletecategorybtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sms/icons/icons8-trash-20 (1).png"))); // NOI18N
        deletecategorybtn.setText("Delete");
        deletecategorybtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        deletecategorybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletecategorybtnActionPerformed(evt);
            }
        });

        closelbl2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sms/icons/icons8-close-16.png"))); // NOI18N
        closelbl2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closelbl2MouseClicked(evt);
            }
        });

        minimizelbl2.setForeground(new java.awt.Color(204, 0, 204));
        minimizelbl2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sms/icons/icons8-line-15 (1).png"))); // NOI18N
        minimizelbl2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizelbl2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout categorypanelLayout = new javax.swing.GroupLayout(categorypanel);
        categorypanel.setLayout(categorypanelLayout);
        categorypanelLayout.setHorizontalGroup(
            categorypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(categorypanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(categorypanelLayout.createSequentialGroup()
                .addGroup(categorypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(categorypanelLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(categorypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9)
                            .addComponent(catnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(categorypanelLayout.createSequentialGroup()
                                .addComponent(addcategorybtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(updatecategorybtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deletecategorybtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73))
                    .addComponent(jSeparator2)
                    .addComponent(categoryScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, categorypanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(minimizelbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(closelbl2)))
                .addContainerGap())
        );
        categorypanelLayout.setVerticalGroup(
            categorypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(categorypanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(categorypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(closelbl2)
                    .addComponent(minimizelbl2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(70, 70, 70)
                .addComponent(jLabel9)
                .addGap(32, 32, 32)
                .addComponent(catnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(categorypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addcategorybtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updatecategorybtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deletecategorybtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(categoryScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
        );

        dashboardtabpanel.addTab("c", categorypanel);

        userpanel.setBackground(new java.awt.Color(153, 255, 102));
        userpanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                userpanelComponentShown(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sms/icons/icons8-name-20.png"))); // NOI18N
        jLabel1.setText("FullName");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sms/icons/icons8-lock-20.png"))); // NOI18N
        jLabel2.setText("Password");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sms/icons/icons8-email-20.png"))); // NOI18N
        jLabel3.setText("Email");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sms/icons/icons8-add-user-20.png"))); // NOI18N
        jLabel4.setText("Usertype");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sms/icons/icons8-call-20.png"))); // NOI18N
        jLabel5.setText("Phone");

        usertypecombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "User" }));

        adduserbtn.setBackground(new java.awt.Color(0, 204, 0));
        adduserbtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        adduserbtn.setForeground(new java.awt.Color(255, 255, 255));
        adduserbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sms/icons/icons8-add-20 (1)_1.png"))); // NOI18N
        adduserbtn.setText("Add");
        adduserbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adduserbtnActionPerformed(evt);
            }
        });

        deleteuserbtn.setBackground(new java.awt.Color(255, 0, 0));
        deleteuserbtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        deleteuserbtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteuserbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sms/icons/icons8-trash-20 (1).png"))); // NOI18N
        deleteuserbtn.setText("Delete");
        deleteuserbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteuserbtnMouseClicked(evt);
            }
        });

        updateuserbtn.setBackground(new java.awt.Color(255, 153, 0));
        updateuserbtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        updateuserbtn.setForeground(new java.awt.Color(255, 255, 255));
        updateuserbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sms/icons/icons8-edit-20.png"))); // NOI18N
        updateuserbtn.setText("Update");
        updateuserbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateuserbtnMouseClicked(evt);
            }
        });
        updateuserbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateuserbtnActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        userstable.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        userstable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "FullName", "Phone", "Email", "Password", "Usertype"
            }
        ));
        userstable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userstableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(userstable);

        errorlabel.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        errorlabel.setForeground(new java.awt.Color(255, 153, 0));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sms/icons/icons8-manage-50.png"))); // NOI18N
        jLabel6.setText("Manage User");

        closelbl3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sms/icons/icons8-close-16.png"))); // NOI18N
        closelbl3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closelbl3MouseClicked(evt);
            }
        });

        minimizelbl3.setForeground(new java.awt.Color(204, 0, 204));
        minimizelbl3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sms/icons/icons8-line-15 (1).png"))); // NOI18N
        minimizelbl3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizelbl3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout userpanelLayout = new javax.swing.GroupLayout(userpanel);
        userpanel.setLayout(userpanelLayout);
        userpanelLayout.setHorizontalGroup(
            userpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userpanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(userpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userpanelLayout.createSequentialGroup()
                        .addGroup(userpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userphonetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(76, 76, 76)
                        .addGroup(userpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usertypecombo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(userpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(userpanelLayout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addComponent(adduserbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(48, 48, 48)
                            .addComponent(updateuserbtn)
                            .addGap(35, 35, 35)
                            .addComponent(deleteuserbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(userpanelLayout.createSequentialGroup()
                            .addGroup(userpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(useremailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(76, 76, 76)
                            .addGroup(userpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(userpasswordtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(userpanelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(errorlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(userpanelLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(fullnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6))
                .addGroup(userpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userpanelLayout.createSequentialGroup()
                        .addComponent(passwordcheck, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                        .addGap(7, 7, 7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userpanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(minimizelbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(closelbl3)
                        .addContainerGap())))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        userpanelLayout.setVerticalGroup(
            userpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userpanelLayout.createSequentialGroup()
                .addGroup(userpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userpanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(userpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(minimizelbl3)
                        .addComponent(closelbl3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(errorlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(userpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fullnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(userpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(userpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(useremailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userpasswordtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordcheck, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(userpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(userpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userphonetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usertypecombo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(userpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adduserbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteuserbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateuserbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))
        );

        dashboardtabpanel.addTab("u", userpanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dashboardtabpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dashboardtabpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void categorybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categorybtnActionPerformed
        dashboardtabpanel.setSelectedIndex(2);

    }//GEN-LAST:event_categorybtnActionPerformed

    private void userbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userbtnActionPerformed
        dashboardtabpanel.setSelectedIndex(3);

    }//GEN-LAST:event_userbtnActionPerformed

    private void productbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productbtnActionPerformed
        dashboardtabpanel.setSelectedIndex(1);

    }//GEN-LAST:event_productbtnActionPerformed

    private void billingbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billingbtnActionPerformed
        dashboardtabpanel.setSelectedIndex(0);
    }//GEN-LAST:event_billingbtnActionPerformed

    private void pricetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pricetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pricetxtActionPerformed

    private void AddproductbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddproductbtnActionPerformed
        String productname = producttxt.getText();
        Double quantity = Double.valueOf(quantitytxt.getText());
        Double price = Double.valueOf(pricetxt.getText());
        String category = categorycombo.getSelectedItem().toString();
        try {
            String sql = "INSERT INTO `product`(productname,quantity,price,category)VALUES('" + productname + "','" + quantity + "','" + price + "','" + category + "') ";
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
            Statement st = con.createStatement();
            st.executeUpdate(sql);
            DisplayProduct();
            ClearProduct();
            JOptionPane.showMessageDialog(null, "the product has been added  successfully");

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);

        }


    }//GEN-LAST:event_AddproductbtnActionPerformed

    private void logoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbtnActionPerformed
//        new Dashboard().dispose();
//        new Login().setVisible(true);


    }//GEN-LAST:event_logoutbtnActionPerformed

    private void adduserbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adduserbtnActionPerformed
        String fullname = fullnametxt.getText();
        String email = useremailtxt.getText();
        String password = userpasswordtxt.getText();
        String phone = userphonetxt.getText();
        String usertype = usertypecombo.getSelectedItem().toString();
        if (email.trim().isEmpty() || fullname.trim().isEmpty() || phone.trim().isEmpty() || password.trim().isEmpty()) {
            errorlabel.setText("all the fields are required");
        } else if (ValidateEmail(email)) {
            if (!checkEmail(email)) {
                try {
                    String sql = "INSERT INTO `users` (`fullname`, `email`, `phone`, `usertype`, `password`) "
                            + "VALUES ( '" + fullname + "', '" + email + "', '" + phone + "', '" + usertype + "','" + password + "')";
                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
                    Statement st = con.createStatement();
                    st.executeUpdate(sql);
                    DisplayUsers();

                    JOptionPane.showMessageDialog(null, "the user has been added  successfully");
                    ClearUser();
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, e);

                }
            }
        }
//        Connection con =DriverManager.getConnection(url) ;
    }//GEN-LAST:event_adduserbtnActionPerformed

    private void categorycomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categorycomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categorycomboActionPerformed

    private void userstableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userstableMouseClicked
        DefaultTableModel model = (DefaultTableModel) userstable.getModel();
        int myindex = userstable.getSelectedRow();
        key = Integer.valueOf(model.getValueAt(myindex, 0).toString());
        fullnametxt.setText(model.getValueAt(myindex, 1).toString());
        userphonetxt.setText(model.getValueAt(myindex, 2).toString());
        useremailtxt.setText(model.getValueAt(myindex, 3).toString());
        userpasswordtxt.setText(model.getValueAt(myindex, 4).toString());
        usertypecombo.setSelectedItem(model.getValueAt(myindex, 5).toString());
    }//GEN-LAST:event_userstableMouseClicked

    private void deleteuserbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteuserbtnMouseClicked
        if (key == 0) {
            JOptionPane.showMessageDialog(null, "select a user to delete from the table");
        } else {
            try {
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");

                String sql = "Delete from users where id =" + key;
                Statement del = con.createStatement();
                del.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "user deleted successfully");
                DisplayUsers();

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
    }//GEN-LAST:event_deleteuserbtnMouseClicked

    private void userpanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_userpanelComponentShown
        DisplayUsers();
    }//GEN-LAST:event_userpanelComponentShown

    private void updateuserbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateuserbtnMouseClicked
        if (useremailtxt.getText().trim().isEmpty() || fullnametxt.getText().trim().isEmpty() || userphonetxt.getText().trim().isEmpty() || userpasswordtxt.getText().trim().isEmpty()) {
            errorlabel.setText("all the fields are required");
        } else if (ValidateEmail(useremailtxt.getText())) {
            if (!checkEmail(useremailtxt.getText())) {
                try {
                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");

                    String sql = "UPDATE users set fullname=?,email=?,phone=?,password=?,usertype=? WHERE id=?";
                    PreparedStatement pst = con.prepareStatement(sql);

                    pst.setString(1, fullnametxt.getText());
                    pst.setString(2, useremailtxt.getText());
                    pst.setString(3, userphonetxt.getText());
                    pst.setString(4, userpasswordtxt.getPassword().toString());
                    pst.setString(5, usertypecombo.getSelectedItem().toString());
                    pst.setInt(6, key);
                    if (pst.executeUpdate() == 1) {

                        DisplayUsers();

                        JOptionPane.showMessageDialog(null, "user details updated  successfully");
                        ClearUser();
                    }
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, ex);
                }
            }
        }
    }//GEN-LAST:event_updateuserbtnMouseClicked

    private void updateuserbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateuserbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateuserbtnActionPerformed

    private void addcategorybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcategorybtnActionPerformed
        String categoryname = catnametxt.getText();
        if (!categoryname.isEmpty()) {
            try {
                String sql = "INSERT INTO category (categoryname)VALUES('" + categoryname + "')";
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
                Statement st = con.createStatement();
                st.executeUpdate(sql);
                DisplayCategory();
                JOptionPane.showMessageDialog(null, "category has been saved");
                ClearCategory();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }

    }//GEN-LAST:event_addcategorybtnActionPerformed

    private void updatecategorybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatecategorybtnActionPerformed
        try {
            String sql = "UPDATE category SET categoryname=? WHERE id=?";
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
            PreparedStatement pst = con.prepareStatement(sql);

            pst.setString(1, catnametxt.getText());
            pst.setInt(2, key);
            DisplayCategory();
            if (pst.executeUpdate() == 1) {

                DisplayCategory();

                JOptionPane.showMessageDialog(null, "category name updated  successfully");
                ClearCategory();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_updatecategorybtnActionPerformed

    private void categorytableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categorytableMouseClicked
        DefaultTableModel model = (DefaultTableModel) categorytable.getModel();
        int myindex = categorytable.getSelectedRow();
        key = Integer.valueOf(model.getValueAt(myindex, 0).toString());
        catnametxt.setText(model.getValueAt(myindex, 1).toString());
    }//GEN-LAST:event_categorytableMouseClicked

    private void deletecategorybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletecategorybtnActionPerformed
        if (key == 0) {
            JOptionPane.showMessageDialog(null, "select a category you want  to delete from the table");
        } else {
            try {
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");

                String sql = "Delete from category where id =" + key;
                Statement del = con.createStatement();
                del.executeUpdate(sql);
                DisplayCategory();
                JOptionPane.showMessageDialog(null, "category deleted successfully");

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
    }//GEN-LAST:event_deletecategorybtnActionPerformed

    private void categorypanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_categorypanelComponentShown
        DisplayCategory();        // TODO add your handling code here:
    }//GEN-LAST:event_categorypanelComponentShown

    private void productpanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_productpanelComponentShown
        LoadCategory();
        DisplayProduct();

    }//GEN-LAST:event_productpanelComponentShown

    private void UpdateproductbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateproductbtnMouseClicked
        try {
            String sql = "UPDATE product SET productname=?,quantity=?,price=?,category=? WHERE id=?";
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
            PreparedStatement pst = con.prepareStatement(sql);

            pst.setString(1, producttxt.getText());
            pst.setDouble(2, Double.valueOf(quantitytxt.getText()));
            pst.setDouble(3, Double.valueOf(pricetxt.getText()));
            pst.setString(4, categorycombo.getSelectedItem().toString());
            pst.setInt(5, key);
            DisplayProduct();
            if (pst.executeUpdate() == 1) {
                DisplayProduct();

                JOptionPane.showMessageDialog(null, "product details updated  successfully");
                ClearProduct();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_UpdateproductbtnMouseClicked

    private void DeleteproductbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteproductbtnMouseClicked
        if (key == 0) {
            JOptionPane.showMessageDialog(null, "select product  to  be deleted from the table");
        } else {
            try {
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");

                String sql = "Delete from product where id =" + key;
                Statement del = con.createStatement();
                del.executeUpdate(sql);
                DisplayProduct();
                JOptionPane.showMessageDialog(null, "product deleted successfully");

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
    }//GEN-LAST:event_DeleteproductbtnMouseClicked

    private void producttableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_producttableMouseClicked
        DefaultTableModel model = (DefaultTableModel) producttable.getModel();
        int myindex = producttable.getSelectedRow();
        key = Integer.valueOf(model.getValueAt(myindex, 0).toString());
        producttxt.setText(model.getValueAt(myindex, 1).toString());
        quantitytxt.setText(model.getValueAt(myindex, 2).toString());
        pricetxt.setText(model.getValueAt(myindex, 3).toString());
        categorycombo.setSelectedItem(model.getValueAt(myindex, 4).toString());


    }//GEN-LAST:event_producttableMouseClicked

    private void billpanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_billpanelComponentShown
        DisplayBills();
    }//GEN-LAST:event_billpanelComponentShown

    private void logoutbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutbtnMouseClicked
this.dispose();
        new Login().setVisible(true);
        

    }//GEN-LAST:event_logoutbtnMouseClicked

    private void closelblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closelblMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closelblMouseClicked

    private void minimizelblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizelblMouseClicked
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizelblMouseClicked

    private void closelbl1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closelbl1MouseClicked
        System.exit(0);    }//GEN-LAST:event_closelbl1MouseClicked

    private void UpdateproductbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateproductbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateproductbtnActionPerformed

    private void minimizelbl1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizelbl1MouseClicked
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizelbl1MouseClicked

    private void closelbl2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closelbl2MouseClicked
        System.exit(0);    }//GEN-LAST:event_closelbl2MouseClicked

    private void minimizelbl2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizelbl2MouseClicked
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizelbl2MouseClicked

    private void closelbl3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closelbl3MouseClicked
        System.exit(0);    }//GEN-LAST:event_closelbl3MouseClicked

    private void minimizelbl3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizelbl3MouseClicked
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizelbl3MouseClicked

    public boolean checkEmail(String email) {
        PreparedStatement pst;
        ResultSet rs;
        boolean email_exist = false;
        try {
            String query = "SELECT*FROM `users` WHERE email=?";
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
            pst = con.prepareStatement(query);
            pst.setString(1, email);
            rs = pst.executeQuery();

            if (rs.next()) {
                email_exist = true;
                JOptionPane.showMessageDialog(null, "The email used is already registered", "Email Failed", 2);
            }
        } catch (Exception e) {
            System.out.println(e);
        }
        return email_exist;
    }

    public boolean ValidateEmail(String email) {
        boolean valid_email = true;
        if (!(Pattern.matches("^[a-zA-Z0-9]+[@]{1}+[a-zA-Z0-9]+[.]{1}+[a-zA-Z0-9]+$", email))) {
            valid_email = false;
            JOptionPane.showMessageDialog(null, "please enter a valid email address", "Error", JOptionPane.ERROR_MESSAGE);
        }

        return valid_email;
    }

    private void DisplayUsers() {
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");

            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("Select* from users");
            userstable.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    private void DisplayCategory() {
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");

            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("Select* from category");
            categorytable.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    private void DisplayProduct() {
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");

            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("Select* from product");
            producttable.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    public void LoadCategory() {
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");

            String sql = "SELECT * FROM category";
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery(sql);
            while (rs.next()) {
                String catname = rs.getString("categoryname");
                categorycombo.addItem(catname);

            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    private void DisplayBills() {
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");

            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("Select* from bill");
            billtable.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    private void ClearProduct() {
        producttxt.setText("");
        quantitytxt.setText("");
        pricetxt.setText("");
    }

    private void ClearUser() {
        fullnametxt.setText("");
        useremailtxt.setText("");
        userpasswordtxt.setText("");
        userphonetxt.setText("");
    }

    private void ClearCategory() {
        catnametxt.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Addproductbtn;
    private javax.swing.JButton Deleteproductbtn;
    private javax.swing.JButton Updateproductbtn;
    private javax.swing.JButton addcategorybtn;
    private javax.swing.JButton adduserbtn;
    private javax.swing.JButton billingbtn;
    private javax.swing.JPanel billpanel;
    private javax.swing.JTable billtable;
    private javax.swing.JScrollPane categoryScrollPane2;
    private javax.swing.JButton categorybtn;
    private javax.swing.JComboBox<String> categorycombo;
    private javax.swing.JPanel categorypanel;
    private javax.swing.JTable categorytable;
    private javax.swing.JTextField catnametxt;
    private javax.swing.JLabel closelbl;
    private javax.swing.JLabel closelbl1;
    private javax.swing.JLabel closelbl2;
    private javax.swing.JLabel closelbl3;
    private javax.swing.JTabbedPane dashboardtabpanel;
    private javax.swing.JButton deletecategorybtn;
    private javax.swing.JButton deleteuserbtn;
    private javax.swing.JLabel errorlabel;
    private javax.swing.JTextField fullnametxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTree jTree1;
    private javax.swing.JButton logoutbtn;
    private javax.swing.JLabel minimizelbl;
    private javax.swing.JLabel minimizelbl1;
    private javax.swing.JLabel minimizelbl2;
    private javax.swing.JLabel minimizelbl3;
    private javax.swing.JCheckBox passwordcheck;
    private javax.swing.JTextField pricetxt;
    private javax.swing.JScrollPane productScrollPane4;
    private javax.swing.JButton productbtn;
    private javax.swing.JPanel productpanel;
    private javax.swing.JTable producttable;
    private javax.swing.JTextField producttxt;
    private javax.swing.JTextField quantitytxt;
    private javax.swing.JTextField searchcategorytxt;
    private javax.swing.JButton updatecategorybtn;
    private javax.swing.JButton updateuserbtn;
    private javax.swing.JButton userbtn;
    private javax.swing.JTextField useremailtxt;
    private javax.swing.JPanel userpanel;
    private javax.swing.JPasswordField userpasswordtxt;
    private javax.swing.JTextField userphonetxt;
    private javax.swing.JTable userstable;
    private javax.swing.JComboBox<String> usertypecombo;
    // End of variables declaration//GEN-END:variables
}
