/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sms;

import java.util.Date;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Census
 */
public class UserDashboard extends javax.swing.JFrame {

    /**
     * Creates new form UserDashboard
     */
    public UserDashboard() {
        initComponents();
    }
    int key = 0;
    Double AvailQty = 0.0;
    int i = 0;
    Double price, totalproductprice = 0.0, grandtotal = 0.0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        userlogoutbtn = new javax.swing.JButton();
        sellbtn1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        sellspanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        usrquantitytxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        usrproductnametxt = new javax.swing.JTextField();
        usrpricetxt = new javax.swing.JTextField();
        addbillbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        userproductstable = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        billtxt = new javax.swing.JTextArea();
        clearbillbtn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        grandlabel = new javax.swing.JLabel();
        datelb = new javax.swing.JLabel();
        closelbl3 = new javax.swing.JLabel();
        minimizelbl3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sms/icons/icons8-clothes-shop-64.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("USER");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DASHBOARD");

        userlogoutbtn.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        userlogoutbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sms/icons/icons8-power-button-20.png"))); // NOI18N
        userlogoutbtn.setText("Logout");
        userlogoutbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userlogoutbtnMouseClicked(evt);
            }
        });

        sellbtn1.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        sellbtn1.setText("SELLS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userlogoutbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(sellbtn1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)))
                .addGap(85, 85, 85)
                .addComponent(sellbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(userlogoutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(197, 197, 197))
        );

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 204));
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        sellspanel.setBackground(new java.awt.Color(0, 153, 204));
        sellspanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                sellspanelComponentShown(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Product Name");

        usrquantitytxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usrquantitytxtActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Price per Item");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Quantity");

        addbillbtn.setBackground(new java.awt.Color(0, 0, 255));
        addbillbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addbillbtn.setForeground(new java.awt.Color(255, 255, 255));
        addbillbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sms/icons/icons8-add-20 (1)_1.png"))); // NOI18N
        addbillbtn.setText("Add To Bill");
        addbillbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addbillbtnMouseClicked(evt);
            }
        });
        addbillbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbillbtnActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        userproductstable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Product Name", "Quantity", "Price"
            }
        ));
        userproductstable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userproductstableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(userproductstable);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Items in Stock");

        billtxt.setColumns(20);
        billtxt.setRows(5);
        jScrollPane2.setViewportView(billtxt);

        clearbillbtn.setBackground(new java.awt.Color(0, 0, 255));
        clearbillbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        clearbillbtn.setForeground(new java.awt.Color(255, 255, 255));
        clearbillbtn.setText("Clear");
        clearbillbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearbillbtnMouseClicked(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 0, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("SAVE");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 204));
        jLabel9.setText("Total Price");

        grandlabel.setForeground(new java.awt.Color(255, 255, 255));
        grandlabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        closelbl3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sms/icons/icons8-close-16.png"))); // NOI18N
        closelbl3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closelbl3MouseClicked(evt);
            }
        });

        minimizelbl3.setForeground(new java.awt.Color(204, 0, 204));
        minimizelbl3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sms/icons/icons8-line-15 (1).png"))); // NOI18N
        minimizelbl3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizelbl3MouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("BILL");

        javax.swing.GroupLayout sellspanelLayout = new javax.swing.GroupLayout(sellspanel);
        sellspanel.setLayout(sellspanelLayout);
        sellspanelLayout.setHorizontalGroup(
            sellspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sellspanelLayout.createSequentialGroup()
                .addGroup(sellspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sellspanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(sellspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usrproductnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(usrquantitytxt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58)
                        .addGroup(sellspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usrpricetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(sellspanelLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(addbillbtn)))
                .addGroup(sellspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sellspanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(76, 76, 76)
                        .addComponent(clearbillbtn)
                        .addGap(52, 52, 52))
                    .addGroup(sellspanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2))))
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sellspanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(grandlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
            .addGroup(sellspanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sellspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sellspanelLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(sellspanelLayout.createSequentialGroup()
                        .addComponent(datelb, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(sellspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sellspanelLayout.createSequentialGroup()
                                .addComponent(minimizelbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(closelbl3))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sellspanelLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(139, 139, 139))))))
        );
        sellspanelLayout.setVerticalGroup(
            sellspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sellspanelLayout.createSequentialGroup()
                .addGroup(sellspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sellspanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(datelb, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addGroup(sellspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(sellspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(usrproductnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usrpricetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(usrquantitytxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addbillbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(sellspanelLayout.createSequentialGroup()
                        .addGroup(sellspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(closelbl3)
                            .addComponent(minimizelbl3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(sellspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(grandlabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(sellspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clearbillbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("sell", sellspanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sellspanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_sellspanelComponentShown
        DisplayProducts();
        DisplayDate();
    }//GEN-LAST:event_sellspanelComponentShown

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        SaveBill();
        //        billtxt.print();
    }//GEN-LAST:event_jButton3MouseClicked

    private void clearbillbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearbillbtnMouseClicked
        billtxt.setText("");
        usrproductnametxt.setText("");
        usrquantitytxt.setText("");
        usrpricetxt.setText("");
    }//GEN-LAST:event_clearbillbtnMouseClicked

    private void userproductstableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userproductstableMouseClicked
        DefaultTableModel model = (DefaultTableModel) userproductstable.getModel();
        int myindex = userproductstable.getSelectedRow();
        key = Integer.valueOf(model.getValueAt(myindex, 0).toString());
        usrproductnametxt.setText(model.getValueAt(myindex, 1).toString());
        AvailQty = Double.valueOf(model.getValueAt(myindex, 2).toString());
        usrpricetxt.setText(model.getValueAt(myindex, 3).toString());
        //        usrquantitytxt.setText(model.getValueAt(myindex, 2).toString());
    }//GEN-LAST:event_userproductstableMouseClicked

    private void addbillbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbillbtnActionPerformed
        //        String productname = usrproductnametxt.getText();
        //        Double price = Double.valueOf(usrpricetxt.getText());
        //        Double quantity = Double.valueOf(usrquantitytxt.getText());
        ////        Double totalproductprice = Double.valueOf(usertotalpricetxt.getText());
        ////        totalproductprice = totalproductprice * quantity;
        //        if (productname.isEmpty() || usrquantitytxt.getText().isEmpty() || usrpricetxt.getText().isEmpty()) {
        //            JOptionPane.showMessageDialog(null, "all the field are required");
        //        } else if (AvailQty < Double.valueOf(usrquantitytxt.getText())) {
        //            JOptionPane.showMessageDialog(this, "not enough in the stock,choose a lower quantity");
        //        } else {
        //            i++;
        //            totalproductprice = price * quantity;
        //            grandtotal = totalproductprice + grandtotal;
        //            if (i == 1) {
        //                billtxt.setText(billtxt.getText() + "    *************************ooz tailoring shop*****************\n"
        //                        + "\tID  Product Quantity  Price Total\n\t"
        //                        + "" + i + "            " + usrproductnametxt.getText() + "   " + usrquantitytxt.getText() + "  " + usrquantitytxt.getText() + " " + totalproductprice + " \n\t");
        //            } else {
        //                billtxt.setText(billtxt.getText() + i + "" + usrproductnametxt.getText() + "   " + usrquantitytxt.getText() + "  " + usrquantitytxt.getText() + " " + totalproductprice + " \n\t");
        //            }
        //
        //        }

    }//GEN-LAST:event_addbillbtnActionPerformed

    private void addbillbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addbillbtnMouseClicked
        String productname = usrproductnametxt.getText();
        Double price = Double.valueOf(usrpricetxt.getText());
        Double quantity = Double.valueOf(usrquantitytxt.getText());
        //        Double totalproductprice = Double.valueOf(usertotalpricetxt.getText());
        //        totalproductprice = totalproductprice * quantity;
        if (productname.isEmpty() || usrquantitytxt.getText().isEmpty() || usrpricetxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "all the field are required");
        } else if (AvailQty < Double.valueOf(usrquantitytxt.getText())) {
            JOptionPane.showMessageDialog(this, "not enough in the stock,choose a lower quantity");
        } else {
            i++;
            totalproductprice = price * quantity;
            grandtotal = grandtotal + totalproductprice;
            if (i == 1) {
                billtxt.setText(billtxt.getText()+"************************ Total Bill************************\n"
                        + "\tID \t Product \t Quantity \t PRICE \t TOTAL\n\t"
                        + " "+i+"\t  "+usrproductnametxt.getText()+"\t "+usrquantitytxt.getText()+" \t "+usrpricetxt.getText()+"\t "+totalproductprice+"\n\t");
            } else {
                billtxt.setText(billtxt.getText()+i+" \t   "+usrproductnametxt.getText()+" \t        " + usrquantitytxt.getText()+"  \t   "+usrpricetxt.getText()+" \t       "+totalproductprice+"\n\t");
            }
            grandlabel.setText(Double.valueOf(grandtotal).toString());
            UpdateQuantity();
            Clearbillfields();

        }
    }//GEN-LAST:event_addbillbtnMouseClicked

    private void usrquantitytxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usrquantitytxtActionPerformed
        //        Double price = Double.valueOf(usrpricetxt.getText());
        //        Double quantity = Double.valueOf(usrquantitytxt.getText());
        //        Double totalproductprice = price * quantity;
        //        usertotalpricetxt.setText(totalproductprice);
    }//GEN-LAST:event_usrquantitytxtActionPerformed

    private void closelbl3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closelbl3MouseClicked
        System.exit(0);    }//GEN-LAST:event_closelbl3MouseClicked

    private void minimizelbl3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizelbl3MouseClicked
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizelbl3MouseClicked

    private void userlogoutbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userlogoutbtnMouseClicked
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_userlogoutbtnMouseClicked
    ;    private void Clearbillfields() {
        usrproductnametxt.setText("");
        usrquantitytxt.setText("");
        usrpricetxt.setText("");
    }

    private void DisplayProducts() {
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("Select  id,productname,quantity,price from product");
            userproductstable.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    private void DisplayDate() {
        Date d = new Date();
        SimpleDateFormat f = new SimpleDateFormat("dd-MM-YYYY");
        datelb.setText(f.format(d));
    }

    private void SaveBill() {
        Double total = Double.valueOf(grandlabel.getText());
        String tdate = datelb.getText();

        try {
            String sql = "INSERT INTO `bill`(date,total_amount)VALUES('" + tdate + "','" + total + "') ";
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
            Statement st = con.createStatement();
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Bill saved");

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);

        }
    }

    private void UpdateQuantity() {
        try {
            Double newqty = AvailQty - Double.valueOf(usrquantitytxt.getText());
            String sql = "UPDATE product SET quantity=? WHERE id=?";
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setDouble(1, newqty);
            pst.setInt(2, key);

            if (pst.executeUpdate() == 1) {
                DisplayProducts();
                JOptionPane.showMessageDialog(null, "Items Updated");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    public void CountBills() {
//        try{
//            String sql="SELECT MAX(id) FROM bill";
//            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "root");
//            Statement st = con.createStatement();
//            ResultSet rs=st.executeQuery(sql);
//            rs.next();
//            id=rs.getInt(1)+1;
//        }
//        catch(SQLException ex){
//            
//        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbillbtn;
    private javax.swing.JTextArea billtxt;
    private javax.swing.JButton clearbillbtn;
    private javax.swing.JLabel closelbl3;
    private javax.swing.JLabel datelb;
    private javax.swing.JLabel grandlabel;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel minimizelbl3;
    private javax.swing.JButton sellbtn1;
    private javax.swing.JPanel sellspanel;
    private javax.swing.JButton userlogoutbtn;
    private javax.swing.JTable userproductstable;
    private javax.swing.JTextField usrpricetxt;
    private javax.swing.JTextField usrproductnametxt;
    private javax.swing.JTextField usrquantitytxt;
    // End of variables declaration//GEN-END:variables
}
